name: rudolph
favicon: null
layout_spectrum: 0.1075269
typography_spectrum: 0.1433692
title: Rudolph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E9E9E9'
    - '#1F1F1F'
    - '#B4B4B4'
  brandStrength: 0.6854022
  lightness: 0.4093989
  saturation: 0.6164874
  rhythmicContrast: 0.314174
purpose: []
